server:
  port: 9221
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
spring:
  application:
    name: gateway-center
#更fine-grained（细粒度）配置 serviceId 可以换成url 经过测试只配置这么多不能提供负载均衡
zuul:
  routes:
    vuemail-order-v1:
      path: /order/**
      stripPrefix: false  #局部配置
    vuemail-integrate:
      path: /integrate-path/**
logging:
  level:
    com.netflix: debug